[package]
name = "timekpr-ui-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
actix-web = "4.9"
actix-files = "0.6"
actix-cors = "0.7"

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# Database
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "chrono", "json", "migrate"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# SSH client
russh = "0.45"
russh-keys = "0.45"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Password hashing
argon2 = "0.5"

# Background scheduling
tokio-cron-scheduler = "0.13"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Template engine
askama = { version = "0.12", features = ["with-actix-web"] }

# Environment variables
dotenvy = "0.15"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# HTTP types
actix-web-httpauth = "0.8"

# Random generation and encoding
rand = "0.8"
base64 = "0.22"

# Auto-generated OpenAPI documentation
utoipa = { version = "4.2", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "6.0", features = ["actix-web"] }

# JWT authentication
jsonwebtoken = "9.3"

# Async traits
async-trait = "0.1"

# Directory utilities (replacement for deprecated std::env::home_dir)
dirs = "5.0"

[dev-dependencies]
# Testing
actix-rt = "2.10"
tempfile = "3.10"
