services:
  # Rust Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.rust
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./ssh:/app/ssh:ro
    environment:
      - DATABASE_URL=sqlite:instance/timekpr.db
      - RUST_LOG=info
    networks:
      - timekpr-network

  # Frontend (Nginx serving static HTML/JS)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - timekpr-network

networks:
  timekpr-network:
    driver: bridge